
target 'OpportunityHack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'BraintreeDropIn'
  pod 'ARSLineProgress'
end
